### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by GoodTimeNET** [yangbo1973/TAT4SRec#3]
请问当前代码就是最新版本的代码吗？ 看到代码更新时间为2年前，但您发表的 A time-aware self-attention based neural network model for sequential recommendation 是在23年，并且看到readme.md 文件，发现题目都不对，着令人担心。

**Comment by yangbo1973** [comment]
这是最新的代码，上次更新时间为两年前是因为期刊论文整体审稿流程较长，题目是因为期刊编辑要求修改。

**Comment by GoodTimeNET** [comment]
ok，感谢您在序列推荐中所做出的贡献。感激不尽。
